[project]
name = "cli-assistant"
version = "0.1.0"
description = "AI-powered CLI Assistant with OpenAI integration for contacts and notes management"
authors = [
    {name = "Univer AI ML"}
]
readme = "README.md"
requires-python = ">=3.9,<3.14"
dependencies = [
    "openai>=1.97.0,<2.0.0",
    "questionary>=2.0.0,<3.0.0",
    "rich>=13.0.0,<14.0.0",
    "tabulate>=0.9.0,<1.0.0",
]

[project.scripts]
cli-assistant = "cli_assistant.main:main"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
packages = [{include = "cli_assistant", from = "src"}]

[tool.poetry.dependencies]
python = ">=3.9,<3.14"
# Core dependencies
openai = ">=1.97.0,<2.0.0"
questionary = ">=2.0.0,<3.0.0"
rich = ">=13.0.0,<14.0.0"
tabulate = ">=0.9.0,<1.0.0"

[tool.poetry.group.dev.dependencies]
pytest = "^8.0.0"
pytest-cov = "^4.0.0"
black = "^24.0.0"
isort = "^5.13.0"
flake8 = "^7.0.0"
mypy = "^1.8.0"

[tool.poetry.scripts]
cli-assistant = "cli_assistant.main:main"

[[tool.poetry.source]]
name = "PyPI"
priority = "primary"

[tool.black]
line-length = 88
target-version = ['py39', 'py310', 'py311', 'py312', 'py313']

[tool.isort]
profile = "black"
multi_line_output = 3

[tool.mypy]
python_version = "3.9"
warn_return_any = true
warn_unused_configs = true
disallow_untyped_defs = true

[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = ["test_*.py", "*_test.py", "tests_*.py"]
python_classes = ["Test*"]
python_functions = ["test_*"]
addopts = "-v --tb=short --junit-xml=test-results.xml"
minversion = "6.0"
