name: Tests
on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
  workflow_dispatch:  # Позволяет запускать тесты вручную через GitHub UI
    inputs:
      debug:
        description: 'Enable debug mode'
        required: false
        default: false
        type: boolean
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.13"]
    steps:
    - uses: actions/checkout@v4
   
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
   
    - name: Install Poetry
      uses: snok/install-poetry@v1
      with:
        version: latest
        virtualenvs-create: true
        virtualenvs-in-project: true
        installer-parallel: true
   
    - name: Load cached venv
      id: cached-poetry-dependencies
      uses: actions/cache@v4
      with:
        path: .venv
        key: venv-${{ runner.os }}-${{ matrix.python-version }}-${{ hashFiles('**/poetry.lock') }}
   
    - name: Check and update lock file
      run: |
        if ! poetry check --lock; then
          echo "Lock file is out of sync, updating..."
          poetry lock
        fi
   
    - name: Install dependencies
      if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'
      run: poetry install --no-interaction --no-ansi
   
    - name: Run tests
      run: |
        if [ "${{ github.event.inputs.debug }}" == "true" ]; then
          poetry run pytest tests/ -v --tb=long -s
        else
          poetry run pytest tests/ -v --tb=short
        fi
   
    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-results-${{ matrix.python-version }}
        path: test-results.xml
        retention-days: 30
   
    - name: Run type checking
      run: |
        poetry run mypy src/
   
    - name: Run code formatting check
      run: |
        poetry run black --check .
       
    - name: Run import sorting check
      run: |
        poetry run isort --check-only .